name: Pay4Me Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Get dependencies
        run: flutter pub get

      - name: Run widget tests
        run: flutter test --no-pub > test_results.txt

      - name: Display test results
        if: always()
        run: |
          echo "Test results:"
          cat test_results.txt || true

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test_results.txt